config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'pages#index'
  get '/about' => 'pages#about'

  resources :dogs
  resources :owners
  resources :vets
  resources :clinics

  root 'pages#index'

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  has_many :vets
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: [:show, :edit, :update, :destroy]

  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.all
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /clinics/1/edit
  def edit
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clinic was successfully created.' }
        format.json { render :show, status: :created, location: @clinic }
      else
        format.html { render :new }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1
  # PATCH/PUT /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to @clinic, notice: 'Clinic was successfully updated.' }
        format.json { render :show, status: :ok, location: @clinic }
      else
        format.html { render :edit }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic.destroy
    respond_to do |format|
      format.html { redirect_to clinics_url, notice: 'Clinic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clinic_params
      params.require(:clinic).permit(:name, :phone, :fax)
    end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.erb
<%= simple_form_for(@clinic) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :phone %>
    <%= f.input :fax %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clinics/edit.html.erb
<h1>Editing Clinic</h1>

<%= render 'form' %>

<%= link_to 'Show', @clinic %> |
<%= link_to 'Back', clinics_path %>

app/views/clinics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clinics</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Fax</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clinics.each do |clinic| %>
      <tr>
        <td><%= clinic.name %></td>
        <td><%= clinic.phone %></td>
        <td><%= clinic.fax %></td>
        <td><%= link_to 'Show', clinic %></td>
        <td><%= link_to 'Edit', edit_clinic_path(clinic) %></td>
        <td><%= link_to 'Destroy', clinic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clinic', new_clinic_path %>

app/views/clinics/new.html.erb
<h1>New Clinic</h1>

<%= render 'form' %>

<%= link_to 'Back', clinics_path %>

app/views/clinics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @clinic.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @clinic.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @clinic.fax %>
</p>

<%= link_to 'Edit', edit_clinic_path(@clinic) %> |
<%= link_to 'Back', clinics_path %>