config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'pages#index'
  get '/about' => 'pages#about'

  resources :dogs
  resources :owners
  resources :vets
  resources :clinics

  root 'pages#index'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :custodies
  has_many :dogs, :through => :custodies
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :phone, :emergency_contact_name, :emergency_contact_phone)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= simple_form_for(@owner) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :phone %>
    <%= f.input :emergency_contact_name %>
    <%= f.input :emergency_contact_phone %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Owners</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Emergency contact name</th>
      <th>Emergency contact phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.first_name %></td>
        <td><%= owner.last_name %></td>
        <td><%= owner.phone %></td>
        <td><%= owner.emergency_contact_name %></td>
        <td><%= owner.emergency_contact_phone %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
  <%= link_to "New Owner", new_dog_path, class: "btn btn-default" %>
</p>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @owner.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @owner.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @owner.phone %>
</p>

<p>
  <strong>Emergency contact name:</strong>
  <%= @owner.emergency_contact_name %>
</p>

<p>
  <strong>Emergency contact phone:</strong>
  <%= @owner.emergency_contact_phone %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>